export const mockClothingProducts = [
  {
    id: 1,
    name: "Áo thun nam cotton cổ tròn basic",
    category: "Áo",
    price: 79000,
    oldPrice: 129000,
    description: "Chất liệu cotton 100%, thấm hút mồ hôi tốt, form suông.",
    image: "https://down-vn.img.susercontent.com/file/1.jpg",
    inStock: true,
    rating: 4.5,
    tags: ["Best Seller", "-39%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Áo sơ mi trắng tay dài form slim",
    category: "Áo",
    price: 159000,
    oldPrice: 199000,
    description: "Áo sơ mi lịch sự, phù hợp đi học và đi làm.",
    image: "https://down-vn.img.susercontent.com/file/2.jpg",
    inStock: true,
    rating: 4.6,
    tags: ["Flash Sale"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
       {
        color: "Vàng",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 0 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Áo hoodie unisex nỉ bông mùa đông",
    category: "Áo",
    price: 229000,
    oldPrice: 299000,
    description: "Áo hoodie dày dặn, giữ ấm tốt, thiết kế trẻ trung.",
    image: "https://down-vn.img.susercontent.com/file/3.jpg",
    inStock: false,
    rating: 4.4,
    tags: ["Hết hàng", "-23%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Áo polo nam thể thao co giãn 4 chiều",
    category: "Áo",
    price: 115000,
    oldPrice: 149000,
    description:
      "Chất vải mịn, thoáng mát, mặc chơi thể thao hay đi chơi đều phù hợp.",
    image: "https://down-vn.img.susercontent.com/file/4.jpg",
    inStock: true,
    rating: 4.3,
    tags: ["Rẻ Vô Địch"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Quần jean ống đứng nam cao cấp",
    category: "Quần",
    price: 199000,
    oldPrice: 249000,
    description: "Quần jean bền đẹp, co giãn nhẹ, phong cách trẻ trung.",
    image: "https://down-vn.img.susercontent.com/file/5.jpg",
    inStock: true,
    rating: 4.7,
    tags: ["-20%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Quần tây công sở slimfit",
    category: "Quần",
    price: 189000,
    oldPrice: 229000,
    description: "Thiết kế sang trọng, phù hợp môi trường văn phòng.",
    image: "https://down-vn.img.susercontent.com/file/6.jpg",
    inStock: false,
    rating: 4.5,
    tags: ["Hết hàng"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 7,
    name: "Quần short nam thể thao vải gió",
    category: "Quần",
    price: 75000,
    oldPrice: 99000,
    description: "Thích hợp mặc đi tập gym, chạy bộ, nhẹ và thoáng.",
    image: "https://down-vn.img.susercontent.com/file/7.jpg",
    inStock: true,
    rating: 4.2,
    tags: ["Flash Sale"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 8,
    name: "Quần jogger kaki nam cá tính",
    category: "Quần",
    price: 145000,
    oldPrice: 189000,
    description: "Phong cách năng động, dễ phối đồ, chất kaki co giãn.",
    image: "https://down-vn.img.susercontent.com/file/8.jpg",
    inStock: true,
    rating: 4.4,
    tags: ["-23%", "Best Seller"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 9,
    name: "Giày sneaker nam cổ thấp màu trắng",
    category: "Giày",
    price: 249000,
    oldPrice: 299000,
    description: "Giày sneaker phong cách Hàn Quốc, form chuẩn.",
    image: "https://down-vn.img.susercontent.com/file/9.jpg",
    inStock: true,
    rating: 4.6,
    tags: ["Trendy"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 10,
    name: "Giày thể thao chạy bộ đế cao su",
    category: "Giày",
    price: 279000,
    oldPrice: 349000,
    description: "Đế chống trượt, nhẹ và thoải mái cho vận động.",
    image: "https://down-vn.img.susercontent.com/file/10.jpg",
    inStock: false,
    rating: 4.3,
    tags: ["Out of Stock", "-20%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 11,
    name: "Giày lười nam da PU công sở",
    category: "Giày",
    price: 219000,
    oldPrice: 269000,
    description: "Phù hợp đi làm, da mềm dễ mang, kiểu dáng lịch sự.",
    image: "https://down-vn.img.susercontent.com/file/11.jpg",
    inStock: true,
    rating: 4.1,
    tags: ["Classic", "-18%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 12,
    name: "Giày boot nam cổ cao cá tính",
    category: "Giày",
    price: 329000,
    oldPrice: 399000,
    description: "Boot da mềm, đế chắc chắn, phong cách mạnh mẽ.",
    image: "https://down-vn.img.susercontent.com/file/12.jpg",
    inStock: true,
    rating: 4.8,
    tags: ["Hot", "-17%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 13,
    name: "Áo khoác gió chống nước nam",
    category: "Áo",
    price: 199000,
    oldPrice: 259000,
    description: "Chống mưa nhẹ, chất liệu nhẹ thoáng, có mũ trùm.",
    image: "https://down-vn.img.susercontent.com/file/13.jpg",
    inStock: true,
    rating: 4.5,
    tags: ["Kháng nước", "-23%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 14,
    name: "Áo len cổ tròn nam mùa đông",
    category: "Áo",
    price: 179000,
    oldPrice: 219000,
    description: "Chất len mềm, giữ ấm tốt, mặc đi làm hay đi chơi.",
    image: "https://down-vn.img.susercontent.com/file/14.jpg",
    inStock: false,
    rating: 4.2,
    tags: ["Mùa đông", "Sold out"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 15,
    name: "Quần thể thao jogger nam co giãn",
    category: "Quần",
    price: 99000,
    oldPrice: 129000,
    description:
      "Vải thun lạnh, co giãn 4 chiều, mặc nhà hay tập gym đều phù hợp.",
    image: "https://down-vn.img.susercontent.com/file/15.jpg",
    inStock: true,
    rating: 4.6,
    tags: ["Gym", "-23%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 16,
    name: "Giày thể thao sneaker vải canvas",
    category: "Giày",
    price: 199000,
    oldPrice: 239000,
    description: "Phong cách đơn giản dễ phối đồ, đế cao su mềm.",
    image: "https://down-vn.img.susercontent.com/file/16.jpg",
    inStock: true,
    rating: 4.4,
    tags: ["Canvas", "-17%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 17,
    name: "Áo sơ mi caro nam dài tay",
    category: "Áo",
    price: 139000,
    oldPrice: 179000,
    description: "Áo caro trẻ trung, chất vải mịn, dễ phối đồ.",
    image: "https://down-vn.img.susercontent.com/file/17.jpg",
    inStock: true,
    rating: 4.2,
    tags: ["Trendy"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 18,
    name: "Quần short kaki nam basic",
    category: "Quần",
    price: 89000,
    oldPrice: 129000,
    description: "Quần short form đẹp, chất kaki dày dặn.",
    image: "https://down-vn.img.susercontent.com/file/18.jpg",
    inStock: true,
    rating: 4.3,
    tags: ["Giảm giá", "-31%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 19,
    name: "Giày da lười nam kiểu công sở",
    category: "Giày",
    price: 279000,
    oldPrice: 329000,
    description: "Da PU mềm, kiểu dáng lịch lãm phù hợp dân văn phòng.",
    image: "https://down-vn.img.susercontent.com/file/19.jpg",
    inStock: false,
    rating: 4.0,
    tags: ["Sale", "Out of Stock"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
  {
    id: 20,
    name: "Giày sneaker nam phối màu năng động",
    category: "Giày",
    price: 299000,
    oldPrice: 369000,
    description: "Thiết kế phối màu trẻ trung, chất liệu êm chân.",
    image: "https://down-vn.img.susercontent.com/file/20.jpg",
    inStock: true,
    rating: 4.6,
    tags: ["Mới về", "-19%"],
    variants: [
      {
        color: "Trắng",
        sizes: [
          { size: "S", quantity: 12 },
          { size: "M", quantity: 30 },
          { size: "L", quantity: 18 },
          { size: "XL", quantity: 0 },
        ],
      },
      {
        color: "Đen",
        sizes: [
          { size: "S", quantity: 5 },
          { size: "M", quantity: 20 },
          { size: "L", quantity: 10 },
          { size: "XL", quantity: 2 },
        ],
      },
    ],
  },
];

export const mockReview = [
  {
    id: 1,
    productId: 1,
    username: "Nguyễn Văn A",
    avatarUrl: "https://i.pravatar.cc/150?img=3",
    rating: 4,
    contents: [
      { type: "text", content: "Sản phẩm rất tốt, đóng gói cẩn thận." },
      { type: "image", content: "https://via.placeholder.com/120x80" },
    ],
  },
];
